### ISSUE TITLE
When I ran the OFA pruning encountered the problems

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1103]
When I ran the OFA pruning in the pytorch demo, I encountered the following problems:

Traceback (most recent call last):
  File "mynet_ofa_pruning.py", line 359, in <module>
    args.excludes)
  File "/opt/vitis_ai/conda/envs/vitis-ai-optimizer_pytorch/lib/python3.7/site-packages/pytorch_nndct/pruning/ofa.py", line 189, in ofa_model
    mod_util.replace_modules(model, name, dynamic_modules, copy_ckpt=True)
  File "/opt/vitis_ai/conda/envs/vitis-ai-optimizer_pytorch/lib/python3.7/site-packages/pytorch_nndct/utils/module_util.py", line 154, in replace_modules
    load_modules_ckpt_copy(modules[i], new_modules[i])
  File "/opt/vitis_ai/conda/envs/vitis-ai-optimizer_pytorch/lib/python3.7/site-packages/pytorch_nndct/utils/module_util.py", line 79, in load_modules_ckpt_copy
    new_modules.conv.weight.data.copy_(old_modules.weight.data)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

**Comment by DehuaTang** [comment]
Sorry, I didn't reproduce this issue.
