### ISSUE TITLE
vitis-ai  tensorflow compiler error   AssertionError: [ERROR] xnnc conv2d op requires one input of 4 dimensions: actual: 1.

### ISSUE THREAD

**Issue by mlopezpalma** [Xilinx/Vitis-AI#1120]
I am using the docker 

CONTAINER ID   IMAGE                        COMMAND   CREATED       STATUS       PORTS     NAMES
f8af351f3961   xilinx/vitis-ai-cpu:latest   "bash"    11 days ago   Up 11 days             cranky_hamilton

When I quantize  the attached model  ,  I found  no error  ; but  when  I compile   I found
AssertionError: [ERROR] xnnc conv2d op requires one input of 4 dimensions: actual: 1.

the output  is  

(vitis-ai-tensorflow2) Vitis-AI /workspace > python3 quantize.py 
2022-12-30 02:59:01.926583: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/xilinx/xrt/lib:/usr/lib:/usr/lib/x86_64-linux-gnu
2022-12-30 02:59:01.926601: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

------------------------------------
TensorFlow version :  2.8.0
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]
------------------------------------
Command line options:
 --float_model  :  build/float_model/f_model.h5
 --quant_model  :  build/quant_model/q_model.h5
 --batchsize    :  50
 --tfrec_dir    :  build/tfrecords
 --evaluate     :  False
------------------------------------

reading images...
2022-12-30 02:59:03.501014: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/xilinx/xrt/lib:/usr/lib:/usr/lib/x86_64-linux-gnu
2022-12-30 02:59:03.501039: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-30 02:59:03.501053: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] no NVIDIA GPU device is present: /dev/nvidia0 does not exist
2022-12-30 02:59:03.501302: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
(None, 1024, 64, 6)
quantizer done
[VAI INFO] Start CrossLayerEqualization...
10/10 [==============================] - 2s 183ms/step
[VAI INFO] CrossLayerEqualization Done.
[VAI INFO] Start Quantize Calibration...
1/1 [==============================] - 6s 6s/step
[VAI INFO] Quantize Calibration Done.
[VAI INFO] Start Post-Quant Model Refinement...
[VAI INFO] Start Quantize Position Ajustment...
[VAI INFO] Quantize Position Ajustment Done.
[VAI INFO] Post-Quant Model Refninement Done.
[VAI INFO] Start Model Finalization...
[VAI INFO] Model Finalization Done.
[VAI INFO] Quantization Finished.
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
Saved quantized model to build/quant_model/q_model.h5
(vitis-ai-tensorflow2) Vitis-AI /workspace > ./compile.sh zcu104
-----------------------------------------
COMPILING MODEL FOR ZCU104..
-----------------------------------------
[INFO] Namespace(batchsize=1, inputs_shape=None, layout='NHWC', model_files=['build/quant_model/q_model.h5'], model_type='tensorflow2', named_inputs_shape=None, out_filename='/tmp/saqibcnn_DPUCZDX8G_ISA1_B4096_org.xmodel', proto=None)
[INFO] tensorflow2 model: /workspace/build/quant_model/q_model.h5
[INFO] keras version: 2.8.0
[INFO] Tensorflow Keras model type: functional
[INFO] parse raw model     :100%|██████████| 29/29 [00:00<00:00, 15108.04it/s]               
[INFO] infer shape (NHWC)  : 92%|█████████▏| 36/39 [00:00<00:00, 191.82it/s]                 
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/bin/xnnc-run", line 33, in <module>
    sys.exit(load_entry_point('xnnc==2.5.1', 'console_scripts', 'xnnc-run')())
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/__main__.py", line 49, in main
    runner.normal_run(args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/runner.py", line 123, in normal_run
    target=target,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/xconverter.py", line 145, in run
    model_files, model_type, _layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/core.py", line 123, in make_xmodel
    model_type=model_t,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 107, in to_xmodel
    model_type,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 177, in create_xmodel
    name, layers, layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 2421, in __create_xmodel_from_tf2
    if not xmodel.infer_shape(Layout.NHWC):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/ir/xmodel.py", line 506, in infer_shape
    ok, error = self.__do_shape_inference(Layout[self.layout])
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/ir/xmodel.py", line 531, in __do_shape_inference
    xnode.infer_shape(layout)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/ir/xnode.py", line 818, in infer_shape
    ), f"[ERROR] xnnc {self.op_type} op requires one input of 4 dimensions: actual: {len(self.inputs_tensor)}."
AssertionError: [ERROR] xnnc conv2d op requires one input of 4 dimensions: actual: 1.
**************************************************
* VITIS_AI Compilation - Xilinx Inc.
**************************************************
-----------------------------------------

MODEL COMPILED
--------------------------------

[f_model.zip](https://github.com/Xilinx/Vitis-AI/files/10324203/f_model.zip)

[q_model.zip](https://github.com/Xilinx/Vitis-AI/files/10324205/q_model.zip)

**Comment by mlopezpalma** [comment]
Many thanks   I can found  the problem and solved
