### ISSUE TITLE
KeyError: 'nndct_hswish' while Fast Finetuning

### ISSUE THREAD

**Issue by jinunyachhyon** [Xilinx/Vitis-AI#1301]
Since Vitis-AI does not support "SiLU" activation, I replaced that with "Hard Swish" for EfficientNet V1. I am getting error during fast fine-tuning, with KeyError: 'nndct_hswish' . This is quantization with Vitis-AI 3.0. 

The replaced code:
``` python
class CNNBlock(nn.Module):
  def __init__(self, in_channels, out_channels, kernel_size, stride, padding, groups=1):
    super(CNNBlock, self).__init__()

    self.cnn = nn.Conv2d(in_channels,
                         out_channels,
                         kernel_size,
                         stride,
                         padding,
                         groups=groups, # 'groups' parameter for depth-wise convolution i.e for each channel independently
                         bias=False)

    self.bn = nn.BatchNorm2d(out_channels)
    self.hard_swish = nn.Hardswish()

  def forward(self, x):
    return self.hard_swish(self.bn(self.cnn(x)))
``` 

Fast fine-tune code:
``` python
from pytorch_nndct.apis import torch_quantizer
quantizer = torch_quantizer(
        quant_mode, model, (input), device=device, quant_config_file=config_file, target=target)

# fast finetune model or load finetuned parameter before test
  if finetune == True:
      ft_loader, _ = load_data(
          subset_len=10,
          train=False,
          batch_size=batch_size,
          sample_method='random',
          model_name=model_name)
      if quant_mode == 'calib':
        quantizer.fast_finetune(evaluate, (quant_model, ft_loader, loss_fn))
      elif quant_mode == 'test':
        quantizer.load_ft_param()
```

The error encountered: 
```
Traceback (most recent call last):
  File "quant.py", line 228, in <module>
    quantization(
  File "quant.py", line 195, in quantization
    quantizer.fast_finetune(evaluate, (quant_model, ft_loader, loss_fn))
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.8/site-packages/pytorch_nndct/apis.py", line 123, in fast_finetune
    self.processor.finetune(run_fn, run_args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.8/site-packages/pytorch_nndct/qproc/base.py", line 293, in finetune
    adaquant.finetune_v2(run_fn, run_args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.8/site-packages/pytorch_nndct/qproc/adaquant.py", line 803, in finetune_v2
    net_loss = self.optimize_layer_v2(qnode, fmod, layer_act_pair, net_inputs, net_outputs, net_loss, device, need_cache)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.8/site-packages/pytorch_nndct/qproc/adaquant.py", line 934, in optimize_layer_v2
    fout = act_func_map[act_node.op.type](fout)
KeyError: 'nndct_hswish'```

**Comment by jtkz** [comment]
I encountered the same issue... and I think I found the root cause:

In https://github.com/Xilinx/Vitis-AI/blob/v3.5/src/vai_optimizer/pytorch_binding/pytorch_nndct/utils/torch_utils.py function compare_torch_version signature looks like this: 

`def compare_torch_version(compare_type:CmpFlag, version:str)`.

Then, in https://github.com/Xilinx/Vitis-AI/blob/v3.5/src/vai_optimizer/pytorch_binding/pytorch_nndct/qproc/adaquant.py (which is the file from which the `KeyError` is thrown), the function is called like this:

`if compare_torch_version('1.6.0',CmpFlag.GREATER_EQUAL):`,

although it should be called like this: 

`if compare_torch_version(CmpFlag.GREATER_EQUAL, '1.6.0'):`, 

i.e. the arguments are given in the wrong order.

Hopefully this will be fixed to the next Vitis AI version.
