### ISSUE TITLE
YOLOv5 Quantization

### ISSUE THREAD

**Issue by 60rw311** [Xilinx/Vitis-AI#1446]
Hi everyone,

I'm trying to quantize the YOLOv5n model from [here](https://github.com/ultralytics/yolov5). I'm using the Vitis-AI v3.0 docker with the following code:

```
import pytorch_nndct
import torch
from pytorch_nndct.apis import torch_quantizer, dump_xmodel
from yolov5.models.common import DetectMultiBackend


device = torch.device("cpu")

# Cargar modelo
model = DetectMultiBackend(weights='yolov5s.pt')

###### CUANTIZACION #######
input = torch.randn([1, 3, 640, 640])
quantizer = torch_quantizer('calib', model, (input), device=device)
quant_model = quantizer.quant_model
quantized_model = quantized_model.to(device)
###########################

quantized_model.eval()
results = quantized_model(rand_in)

# Resultados
quantizer.export_quant_config()

print('\nExprotar XMODEL\n')

quantizer.export_xmodel('./quantized/')

print('\nResultados cargados\n')
```
When I run the script, I encounter the following error:

```
Traceback (most recent call last):
  File "model_quant.py", line 4, in <module>
    from yolov5.models.common import DetectMultiBackend
  File "/workspace/WORK/YOLOv5n/yolov5/models/common.py", line 38, in <module>
    from utils import TryExcept
ModuleNotFoundError: No module named 'utils'
```
Can anyone help me?

**Comment by jacobdbrown4** [comment]
Try running this script inside the yolov5 directory.
