### ISSUE TITLE
pytorch quantization Error

### ISSUE THREAD

**Issue by vasdvczxc** [Xilinx/Vitis-AI#215]
Hello, I'm trying example model(ResNet18) quantization on pytorch. 

However, I'm getting some error about XIR library. This error appear when I ran 'restnet18_quant.py --quant_mode 2'.

This is my error log.

root@System-Product-Name:/workspace/Vitis-AI-Quantizer/vai_q_pytorch/example# python resnet18_quant.py --quant_mode 2

[NNDCT_NOTE]: Loading NNDCT kernels...
-------- Start resnet18 test 

[NNDCT_NOTE]: Quantization test process start up...

[NNDCT_NOTE]: =>Parsing ResNet...

[NNDCT_NOTE]: =>Quantizable module is generated.(quantize_result/ResNet.py)
100%|███████████████████████████████████████████████████████████████| 10/10 [00:02<00:00,  3.51it/s]
loss: 0.369209
top-1 / top-5 accuracy: 0 / 0.332226
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/test_env/lib/python3.7/site-packages/nndct_shared/compile/xgraph.py", line 2, in <module>
    from xir.graph import Graph
ModuleNotFoundError: No module named 'xir.graph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "resnet18_quant.py", line 240, in <module>
    quant_mode=args.quant_mode)
  File "resnet18_quant.py", line 215, in quantization
    dump_xmodel()
  File "/opt/vitis_ai/conda/envs/test_env/lib/python3.7/site-packages/pytorch_nndct/apis/quant_api.py", line 126, in dump_xmodel
    compiler = CompilerFactory.get_compiler("xmodel")
  File "/opt/vitis_ai/conda/envs/test_env/lib/python3.7/site-packages/nndct_shared/compile/compiler_factory.py", line 6, in get_compiler
    from .xir_compiler import XirCompiler
  File "/opt/vitis_ai/conda/envs/test_env/lib/python3.7/site-packages/nndct_shared/compile/xir_compiler.py", line 12, in <module>
    from .xgraph import XGraph
  File "/opt/vitis_ai/conda/envs/test_env/lib/python3.7/site-packages/nndct_shared/compile/xgraph.py", line 7, in <module>
    raise Exception('please install xir package')
Exception: please install xir package

But, I can't find xir library anywhere, so I can't install it.

Could you somebody give me some solution?

That is first error. Another problem occur in quant_mode 0. 

When I ran 'python resnet18_quant.py --quant_mode 0', accuracy is always zero. I don't know why. 

What's even more strange is that at 'quant_mode 1' the accuracy increases to around 0.3~0.4

If anyone knows about this issue, I hope you can help me.

**Comment by TenzinCHW** [comment]
Hi you can install xir using the conda channel they provide. Make sure you've activated the correct environment with conda and then run the following commands.
```
wget -O conda-channel.tar.gz https://www.xilinx.com/bin/public/openDownload?filename=conda-channel_1.2.tar.gz
tar -xzvf conda-channel.tar.g
conda install xir -c ./conda-channel
```
