### ISSUE TITLE
Error on quantization pytorch model 

### ISSUE THREAD

**Issue by david132048** [Xilinx/Vitis-AI#229]
I'm trying to quantize pytorch example model. However, I got an error. 

(vitis-ai-pytorch) yongwon@System-Product-Name:/workspace/tools/Vitis-AI-Quantizer/vai_q_pytorc
h/example$ python resnet18_quant.py --quant_mode calib --subset_len 200

[NNDCT_NOTE]: Loading NNDCT kernels...
-------- Start resnet18 test 
Traceback (most recent call last):
  File "resnet18_quant.py", line 283, in <module>
    file_path=file_path)
  File "resnet18_quant.py", line 212, in quantization
    quant_mode, model, (input), device=device)
TypeError: torch_quantizer() got an unexpected keyword argument 'device'

If anyone knows about this issue, please give me some solution.

**Comment by carrotandjzy** [comment]
Can you show me the message of print (pytorch_nndct.__version__) ?

**Comment by carrotandjzy** [comment]
Can you tell me your vitis-ai version ?

**Comment by david132048** [comment]
My version is 1.3.

I resolve it. 

Thank you.
