### ISSUE TITLE
Issue while running neptune  /render/xdf

### ISSUE THREAD

**Issue by mahinlma** [Xilinx/Vitis-AI#34]
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-neptune/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/vitis_ai/conda/envs/vitis-ai-neptune/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-neptune/lib/python3.6/site-packages/vai/dpuv1/rt/xsnodes/stream.py", line 123, in execute
    pub = self.get_pub()
  File "/opt/vitis_ai/conda/envs/vitis-ai-neptune/lib/python3.6/site-packages/vai/dpuv1/rt/xsnodes/base.py", line 193, in get_pub
    return xstream.Publisher(use_context=self.context)
  File "/opt/vitis_ai/conda/envs/vitis-ai-neptune/lib/python3.6/site-packages/vai/dpuv1/rt/xstream.py", line 198, in __init__
    super(Publisher, self).__init__(path)
  File "/opt/vitis_ai/conda/envs/vitis-ai-neptune/lib/python3.6/site-packages/vai/dpuv1/rt/xstream.py", line 121, in __init__
    self.pclient = plasma.connect(path)
  File "pyarrow/_plasma.pyx", line 846, in pyarrow._plasma.connect
  File "pyarrow/_plasma.pyx", line 290, in pyarrow._plasma.plasma_check_status
  File "pyarrow/error.pxi", line 80, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Could not connect to socket /tmp/plasma-xlnx-vitis-ifpga

**Comment by mahinlma** [comment]
following error occurs whenever starting new service,  but not all the time. 


```
Butler connection failed, exiting after too many errors
python: /usr/include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.


```

**Comment by mahinlma** [comment]
Re-installing XRT and xbutler solved my issue
