### ISSUE TITLE
vai_tensorflow1.0创建量化训练图出错

### ISSUE THREAD

**Issue by zhongjinglian** [Xilinx/Vitis-AI#454]
创建模型的训练量化表时，出现如下错误：
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1607, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 'input' passed int32 expected float while building NodeDef 'pred_mbbox/strided_slice_8/aquant' using Op<name=FixNeuron; signature=input:float -> quantized:float; attr=bit_width:int,default=8; attr=method:int,default=1; attr=mode:int; attr=phase:int; attr=output_dir:string,default=""; attr=quantize_pos:int,default=0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "freeze_ckpt_to_pb.py", line 55, in <module>
    decent_q.CreateQuantizeEvaluationGraph(config=q_config)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/quantize_graph.py", line 460, in CreateQuantizeEvaluationGraph
    MergeNodesFromGraphDef(quantize_eval_graph_def)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/quantize_graph.py", line 363, in MergeNodesFromGraphDef
    AppendNode(node, consumers, existed)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/contrib/decent_q/python/quantize_graph.py", line 315, in AppendNode
    new_op = Operation(node_def, g, inputs=t_inputs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Input 'input' passed int32 expected float while building NodeDef 'pred_mbbox/strided_slice_8/aquant' using Op<name=FixNeuron; signature=input:float -> quantized:float; attr=bit_width:int,default=8; attr=method:int,default=1; attr=mode:int; attr=phase:int; attr=output_dir:string,default=""; attr=quantize_pos:int,default=0>
请问错误原因是什么？

**Comment by xieyi4650** [comment]
@zhongjinglian  根据错误提示, 可能是因为pred_mbbox/strided_slice_8/aquant的输入op, 也就是pred_mbbox/strided_slice_8的数据类型是int32, 而pred_mbbox/strided_slice_8/aquant只接受float的输入.
