### ISSUE TITLE
RuntimeError: Can not extract module name from node

### ISSUE THREAD

**Issue by mathmax12** [Xilinx/Vitis-AI#549]
Trying to follow for qat https://github.com/Xilinx/Vitis-AI/tree/41a397a08139c1a8ddeceedda70a83f33d4f4d4f/tools/Vitis-AI-Quantizer/vai_q_pytorch

But got a errror when do the prepation of quantization.

Did I miss anything?

`              ```
# ipu quantization
		input = torch.randn([1, 3, 256, 256], dtype=torch.float32)
		input = torch.Tensor(input).cuda()
		self.model.cuda()
		self.quantizer = torch_quantizer(quant_mode = 'calib',
									module = self.model,
									input_args = (input),
									bitwidth = 8,
									mix_bit = False,
									qat_proc = True)
		print("------------------->2")
		self.model = self.quantizer.quant_model
		print("------------------->3")`
```

`[VAIQ_WARN]: ['efficient_Unet::efficient_Unet/Sequential/Interpolate[1]/2082']

[VAIQ_WARN]: No quantizable node is found in group:

[VAIQ_WARN]: ['efficient_Unet::efficient_Unet/Sequential/Interpolate[1]/2083']

[VAIQ_WARN]: No quantizable node is found in group:

[VAIQ_WARN]: ['efficient_Unet::efficient_Unet/Sequential/Interpolate[1]/2084']

[VAIQ_NOTE]: =>Exporting quant config.(.qat/quant_info.json)

[VAIQ_WARN]: ['efficient_Unet::efficient_Unet/Sequential/Interpolate[1]/2082']

[VAIQ_WARN]: No quantizable node is found in group:

[VAIQ_WARN]: ['efficient_Unet::efficient_Unet/Sequential/Interpolate[1]/2083']

[VAIQ_WARN]: No quantizable node is found in group:

[VAIQ_WARN]: ['efficient_Unet::efficient_Unet/Sequential/Interpolate[1]/2084']

[VAIQ_NOTE]: =>Exporting quant config.(.qat/quant_info.json)

[VAIQ_NOTE]: =>Get module with quantization.
------------------->2
Traceback (most recent call last):  File "train.py", line 108, in <module>    main(config, args.resume)
  File "train.py", line 58, in main
    train_logger=train_logger)
  File "/opt/xilinx/ipu/ipu/depth/Depth-estimation_train_QAT/trainer/trainer.py", line 110, in __init__
    super(Trainer, self).__init__(model, valid_data_loader, loss, metrics, optimizer, resume, config, train_logger)
  File "/opt/xilinx/ipu/ipu/depth/Depth-estimation_train_QAT/base/base_trainer.py", line 114, in __init__
    self.model = self.quantizer.quant_model
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/apis.py", line 110, in quant_model
    return self.processor.quant_model()
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/quantization/quant_aware_training.py", line 586, in quant_model
    self._trainable_model = self.trainable_model()
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/quantization/quant_aware_training.py", line 307, in trainable_model
    self._pre_check(allow_reused_module)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/quantization/quant_aware_training.py", line 332, in _pre_check
    module_name = mod_util.module_name_from_node(node)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/utils/module_util.py", line 38, in module_name_from_node
    node_name))
RuntimeError: Can not extract module name from node efficient_Unet::efficient_Unet/Sequential/Conv2d[0]/input.2`

**Comment by yuwang-xlnx** [comment]
Hi @mathmax12,

Which version of PyTorch are you using ?
