### ISSUE TITLE
ERROR VAI_C_TENSORFLOW2 

### ISSUE THREAD

**Issue by jamsliva** [Xilinx/Vitis-AI#569]
Hi,

I want to increase precision for my Resnet50 model, so I  implemented fine-tuning instead of standard training. However, when I compile the model, I get errors from vai_c_tensorflow2, and couldn't compile successfully.

[INFO] Namespace(batchsize=1, inputs_shape=None, layout='NHWC', model_files=['/workspace/code/tf2_resnet_xilinx_model/quantized/resnet50_model_quan2_1.h5'], model_type='tensorflow2', named_inputs_shape=None, out_filename='/tmp/Resnet50_org.xmodel', proto=None)
[INFO] tensorflow2 model: /workspace/code/tf2_resnet_xilinx_model/quantized/resnet50_model_quan2_1.h5
[INFO] keras version: 2.4.0
[INFO] Tensorflow Keras model type: functional
[INFO] parse raw model     :  2%|█▊                                                                           | 3/126 [00:00<00:00, 6838.54it/s]                
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/bin/xnnc-run", line 33, in <module>
    sys.exit(load_entry_point('xnnc==1.4.0', 'console_scripts', 'xnnc-run')())
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/__main__.py", line 49, in main
    runner.normal_run(args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/runner.py", line 123, in normal_run
    target=target,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/xconverter.py", line 145, in run
    model_files, model_type, _layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/core.py", line 123, in make_xmodel
    model_type=model_t,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 107, in to_xmodel
    model_type,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 177, in create_xmodel
    name, layers, layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 641, in __create_xmodel_from_tf2
    assert "kernel_pos:0" in quant_info_dict
AssertionError

Any suggestions?

**Comment by kayky233** [comment]
Any suggestions? I  get this error too
