### ISSUE TITLE
AttributeError: '_UserObject' object has no attribute 'get_config'

### ISSUE THREAD

**Issue by Raunak-Singh-Inventor** [Xilinx/Vitis-AI#654]
I am in the `vitis-ai-tensorflow2` environment and am trying to quantize `EfficientDet-D0`. 

In my python script, I am able to load the model with tensorflow, but when I run `quantizer = vitis_quantize.VitisQuantizer(float_model)`, the program errors out:
```
Traceback (most recent call last):
  File "quantize.py", line 6, in <module>
    quantizer = vitis_quantize.VitisQuantizer(float_model)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/quantization/keras/vitis/vitis_quantize.py", line 180, in __init__
    self._check_custom_objects()
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/quantization/keras/vitis/vitis_quantize.py", line 429, in _check_custom_objects
    custom_layer_type = self._find_unregistered_layer()
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/tensorflow_model_optimization/python/core/quantization/keras/vitis/vitis_quantize.py", line 412, in _find_unregistered_layer
    model_config = self._float_model.get_config()
AttributeError: '_UserObject' object has no attribute 'get_config'
```

Steps to reproduce:
clone the Vitis-AI repo
clone this repo, https://github.com/Raunak-Singh-Inventor/EfficientDet-D0-VitisAI/ in the Vitis-AI folder
pull the latest docker image `docker pull xilinix/vitis-ai:latest`
start the docker, `./docker_run.sh xilinx/vitis-ai`
run `conda activate vitis-ai-tensorflow2`
run `python3 quantize.py`

Code used for quantizing the model:
```
import tensorflow as tf
from tensorflow_model_optimization.quantization.keras import vitis_quantize

float_model = tf.keras.models.load_model("EfficientDet-D0-SavedModel")

quantizer = vitis_quantize.VitisQuantizer(float_model)
quantized_model = quantizer.quantize_model()

quantized_model.save("quantized_model.h5")
```
Xilinix Docs: https://www.xilinx.com/html_docs/xilinx2019_2/vitis_doc/tensorflow_2x.html#juy1605081519101

**Comment by Raunak-Singh-Inventor** [comment]
Turns out that `tf.keras.models.load_model` wasn't returning a keras model. That was why this issue was coming up, as the `VitisQuantizer` was expecting a keras model.
