### ISSUE TITLE
vai_q_pytorch: RuntimeError: Caught an unknown exception! - mixing torch.jit.trace and torch.jit.script

### ISSUE THREAD

**Issue by Orchidaceae** [Xilinx/Vitis-AI#669]
I tried quantizing the following [EfficientDet model](https://github.com/Orchidaceae/efficientdet) by running the following code:

```python
from pytorch_nndct.apis import torch_quantizer
import torch

## Import model
PATH_NO_NUMPY_CPU = "/home/ljosefs/Desktop/EffDet/efficientdet/trained_models/no_numpy_cpu_effdet.pth"
model = torch.load(PATH_NO_NUMPY_CPU)
# put model in evaluation mode
model.eval()

# Change from memoryefficient swish to ordinary swish
model.backbone_net.model.set_swish(memory_efficient=False)

device = torch.device("cpu")
quant_mode = 'calib'

## random input tensor
input = torch.randn([1, 3, 512, 512])

quantizer = torch_quantizer(
    quant_mode, model, (input.to(('cpu'))), device=torch.device('cpu'))
```

It resulted in the following error:
```bash
[0;32m[VAIQ_NOTE]: Loading NNDCT kernels...[0m

[0;32m[VAIQ_NOTE]: Quantization calibration process start up...[0m

[0;32m[VAIQ_NOTE]: =>Quant Module is in 'cpu'.[0m

[0;32m[VAIQ_NOTE]: =>Parsing EfficientDet...[0m
Traceback (most recent call last):
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/pdb.py", line 1548, in _runscript
    self.run(statement)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/ljosefs/Desktop/EffDet/efficientdet/vai-quant.py", line 7, in <module>
    import random """
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/apis.py", line 77, in __init__
    custom_quant_ops = custom_quant_ops)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/qproc/base.py", line 122, in __init__
    device=device)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/qproc/utils.py", line 175, in prepare_quantizable_module
    graph = parse_module(module, input_args)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/qproc/utils.py", line 78, in parse_module
    module, input_args)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/parser.py", line 68, in __call__
    raw_graph, raw_params = graph_handler.build_torch_graph(graph_name, module, input_args)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/trace_helper.py", line 44, in build_torch_graph
    raw_graph, raw_params = self._build_raw_graph(graph_name, fw_graph, params)
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/trace_helper.py", line 159, in _build_raw_graph
    const_value = TorchValue(list(fw_node.outputs())[0])
  File "/home/ljosefs/miniconda3/envs/vai-q-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/torch_graph.py", line 184, in __init__
    self._type = str(value.type())
RuntimeError: Caught an unknown exception!
```

I performed some pdb debugging and found out that **the vai_q graph parser stopped at this TorchScript node:**  
```%3271 : Function = prim::Constant[name="_get_image_shape"](), scope: EfficientDet/Anchors[anchors]```

I have successfully performed the ```torch.jit.trace```- test on my model without any trace warnings or other issues. I did however use ```@torch.jit.script``` on some functions containing conditional statements and or loops that the ```torch.jit.trace```, according to documentation, was unable to parse. The first in order of these scripted functions is the "```_get_image_shape```" ([here](https://github.com/Orchidaceae/efficientdet/blob/9ea02bfca25bbad07f36051b84665ab23f18be96/src/utils.py#L151)) that may seem to be causing the issue here.

I'm wondering if vai_q_pytorch supports [mixing torch.jit tracing and scripting](https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting)? Or is it something else that causes this problem?

**Comment by gau-nernst** [comment]
I faced a similar issue. I don't think Vitis AI supports TorchScript in general. Last time I used a traced model and Vitis Ai would throw errors. Using normal PyTorch was fine though. This is quite troublesome as model definitions must be present inside Vitis AI environment, which forces me to re-implement the model in torch 1.7 and torchvision 0.8.

Commenting here so that I will get updates from this thread. Let me know if you can get Vitis AI working with TorchScript!

**Comment by carrotandjzy** [comment]
So far, the vai_q_pytorch does not support torch script.
