### ISSUE TITLE
KeyError from /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/collections/__init__.py

### ISSUE THREAD

**Issue by MarvS95** [Xilinx/Vitis-AI#680]
Hello, did anyone have a similar error as in the screenshot below when quantizing a model or knows what causes it and how I can solve it?

```
[VAIQ_NOTE]: Processing ops...
██████████████████████████████████████████████████| 373/373 [00:00<00:00, 1716.23it/s, OpInfo: name = SlowFastModel/ResNetBasicHead[head]/22471, type = size]                                                                        
Traceback (most recent call last):
  File "SlowFast_quant.py", line 190, in <module>
    main()
  File "SlowFast_quant.py", line 185, in main
    quantize_model(model, 'calib', device, quant_stub, quant_dataset, args.output_dir, args.batch_size)
  File "SlowFast_quant.py", line 107, in quantize_model
    quantizer = pna.torch_quantizer(quant_mode, model, quant_stub, output_dir=str(output_path), device=device)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/apis.py", line 89, in __init__
    custom_quant_ops = custom_quant_ops)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/qproc/base.py", line 126, in __init__
    device=device)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/qproc/utils.py", line 196, in prepare_quantizable_module
    graph = parse_module(module, input_args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/qproc/utils.py", line 78, in parse_module
    module, input_args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/parser.py", line 72, in __call__
    nndct_graph = self._convert_graph(raw_graph, self._get_device_info(module, input_args))
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/parser.py", line 139, in _convert_graph
    _construct_ret_struct(raw_graph.ret_values().values(), nndct_graph.return_struct)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/parser.py", line 133, in _construct_ret_struct
    end_tensor = self.get_nndct_value(value)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/site-packages/pytorch_nndct/parse/parser.py", line 267, in get_nndct_value
    return tensor_map[value.name]
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: '22479'
```
Thanks for your help.

**Comment by HasinduKariyawasam** [comment]
Hi @MarvS95, 
Were you able to solve this issue? If you have, can you please share the solution? It will be a great help. Thanks in advance!
