### ISSUE TITLE
vai_c_tensorflow2 failing with error

### ISSUE THREAD

**Issue by sbodapati-de** [Xilinx/Vitis-AI#832]
Arch - DPUCZDX8G
Model - Custom
VAI - Vitis 2.0
conda env - vitis-ai-tensorflow2

Our custom implementation passes the quantizer with CLE and Fast Transform enabled. Quantized model is not getting compiled , here is the error , 

(vitis-ai-tensorflow2) Vitis-AI /workspace/detect > vai_c_tensorflow2 -m detect-quantized.h5 -a /opt/vitis_ai/compiler/arch/DPUCZDX8G/KV260/arch.json -o . -n detect
**************************************************
* VITIS_AI Compilation - Xilinx Inc.
**************************************************
[INFO] Namespace(batchsize=1, inputs_shape=None, layout='NHWC', model_files=['detect-quantized.h5'], model_type='tensorflow2', named_inputs_shape=None, out_filename='/tmp/detect_org.xmodel', proto=None)
[INFO] tensorflow2 model: /workspace/detect/detect-quantized.h5
[INFO] keras version: 2.6.0
[INFO] Tensorflow Keras model type: functional
[INFO] parse raw model     : 89%|███████████████████████████████████████████████████████████████████████████████████████████████▌           | 126/141 [00:00<00:00, 30936.15it/s]             
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/bin/xnnc-run", line 33, in <module>
    sys.exit(load_entry_point('xnnc==2.0.0', 'console_scripts', 'xnnc-run')())
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/__main__.py", line 49, in main
    runner.normal_run(args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/runner.py", line 123, in normal_run
    target=target,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/xconverter.py", line 145, in run
    model_files, model_type, _layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/core.py", line 123, in make_xmodel
    model_type=model_t,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 107, in to_xmodel
    model_type,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 177, in create_xmodel
    name, layers, layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/site-packages/xnnc/translator/tensorflow_translator.py", line 2135, in __create_xmodel_from_tf2
    xnode.tmp_params["shape"] = config['shape']
KeyError: 'shape'

**Comment by zhenzhen-Xilinx** [comment]
Hi @sbodapati-de ,
Please provide the floating point model and the quantized model and the code for the quantized model. thanks.

**Comment by qianglin-xlnx** [comment]
Hi @sbodapati-de 
Is this issue solved?
