### ISSUE TITLE
VAI trace Vitis AI analyzer Issue

### ISSUE THREAD

**Issue by AfifaIshtiaq** [Xilinx/Vitis-AI#842]
Why the vai trace output shows a summary for only one subgraph  on the vitis ai analyzer while on svg I have multiple dpu subgraphs
![deeprx_dilation](https://user-images.githubusercontent.com/68226162/173594880-f0373110-e9ed-4a9c-937c-6b2e05220fa8.svg)

![image](https://user-images.githubusercontent.com/68226162/173594557-51453818-c0da-4627-b86e-54d8d4ef58a7.png)

**Comment by li900309** [comment]
the result you got is for the root su-bgraph (a,k.a top-level sub-graph) if you want more detailed profiling result, you can try run vaitrace with "--fine-grained"
![image](https://user-images.githubusercontent.com/7360000/173781923-4b69b678-d289-4399-ace5-35d37f3ff211.png)

**Comment by AfifaIshtiaq** [comment]
> the result you got is for the root sub-graph (a,k.a top-level sub-graph) if you want more detailed profiling result, you can try run vaitrace with "--fine-grained" option https://github.com/Xilinx/Vitis-AI/tree/master/examples/Vitis-AI-Profiler#command-line-usage ![image](https://user-images.githubusercontent.com/7360000/173781923-4b69b678-d289-4399-ace5-35d37f3ff211.png)

I was able to produce fine grained results. Can you please tell me what is meant by runs? Also in fine grained I'm not able to see Vitis AI performance tab anymore how can I get it
![image](https://user-images.githubusercontent.com/68226162/173809332-272405dc-6a2e-4851-b3d1-17645d92200f.png)

**Comment by li900309** [comment]
runs = the number of times this sub-graph is called
about the FPS view, I think in --fine_grained mode the CNN model will be spitted into several subgraphs and executed one-by-one, in this situation the FPS number become meaningless.

**Comment by qianglin-xlnx** [comment]
Hi @AfifaIshtiaq 
Is this issue solved?

**Comment by qianglin-xlnx** [comment]
Closing since no activity for more than 2 weeks, please reopen if you still have question, thanks

**Comment by gunertatar** [comment]
Hi;
I m using Kria KV260 vision board and i executed the tf_resne50 example from the Vitis AI VART. I d like to look at the performance of behavior of the board and used the vaitrace ./resnet50 resnet50.xmodel. After execution i got only " profile_summry.csv, summary.csv, vart_trace.csv, vitis_ai_profile.summary, xrt.run_summary" files. However, when i look around i think, xclbin.ex.run_summary file also should be in the executed file. By the way Vitis unifed software platform and vitis_analyzer version 2021.1.
Is there anyone could help me please? I really need to check all files belongs to execution such as HAL_API Calls, OpenCL data, Data Transfer, DPU, buffer exchange and so on.

Thanks

**Comment by anirudhitagi** [comment]
@gunertatar , I am also facing a similar issue. I am working with ZCU104 and I did the python flow:  `python3 -m vaitrace_py ./resnet50.py 2 /usr/share/vitis_ai_library/models/resnet50/resnet50.xmodel`
It generated the same files that you got. I tried importing the xrt.run_summary on vitis_analyzer, but the graphs and results it shows are missing lot of information.
Have you found any solution?
 
 @qianglin-xlnx  any advice?

**Comment by gunertatar** [comment]
> @anirudhitagi Unfortunately i haven't found any solution yet. And no one has given information about that. If you find please let me know, or vice-versa i ll let you know.

**Comment by li900309** [comment]
hi @anirudhitagi @gunertatar  the file name of result was changed since vitis and xrt 2021.1 version, xclbin.ex.run_summary was replaced by xrt.run_summary, so just import xrt.run_summary to vitis_analyzer.
for more details, you can try vaitrae --fine_grained , and also you can ntry vaitrace --txt which will show a text summary

**Comment by anirudhitagi** [comment]
I see. Thank you for your response.

**Comment by dextroza** [comment]
Hi,
I am getting error when trying to run ai profiler on VART 2.5, petalinux 22.1. I am trying to profile my c++ application on ZCU104.
The code:
`$ vaitrace ./app_zcu104.elf`,
The error occurs at the end of profiling:
`APM Stop Collecting
WARNING:root:Cannot open 'zyxclmm_drm/ip_layout'
INFO:root:Generating VTF
INFO:root:Processing xmodel information
INFO:root:SubGraph index duplication: [subgraph_data_upload_0|0]
Traceback (most recent call last):
  File "/usr/bin/vaitrace", line 186, in <module>
    main(*parseCmdLine())
  File "/usr/bin/vaitrace", line 181, in main
    vaitraceWriter.write(options)
  File "/usr/bin/xlnx/vaitrace/vaitraceWriter.py", line 83, in write
    writer.vtf.convert.xat_to_vtf(rawData)
  File "/usr/bin/xlnx/vaitrace/writer/vtf/convert.py", line 331, in xat_to_vtf
    convert_dpu(xat.get('vart'))
  File "/usr/bin/xlnx/vaitrace/writer/vtf/convert.py", line 140, in convert_dpu
    dpu_profile_summary = dpu_parser.get_dpu_profile_summary()
  File "/usr/bin/xlnx/vaitrace/writer/parser/vart_parser.py", line 334, in get_dpu_profile_summary
    perf = workload * batch / avg_t * 1000  # to GOP/ms
ZeroDivisionError: float division by zero`

How to fix this error? Thanks!
