### ISSUE TITLE
Error when compiling Tensorflow ResNet50 quantized model on Vitis AI Compiler 2.x

### ISSUE THREAD

**Issue by comihai** [Xilinx/Vitis-AI#917]
Hi,
I am trying to compile a ResNet50 network with custom input for ZCU102 board. The definition of ResNet50 model is based on [TensorFlow-Slim implementation](https://github.com/tensorflow/models/blob/master/research/slim/nets/resnet_v1.py). After quantization step, I got an error at compilation step. I included below the output of vai_c_tensorflow tool.
```
**************************************************
* VITIS_AI Compilation - Xilinx Inc.
**************************************************
[INFO] Namespace(batchsize=1, inputs_shape=['1,120,120,10'], layout='NHWC', model_files=['quantize/quantize_eval_model.pb'], model_type='tensorflow', named_inputs_shape=None, out_filename='/tmp/ResNet50_BEN_compiled_org.xmodel', proto=None)
in_shapes: [[1, 120, 120, 10]]
[INFO] tensorflow model: /workspace/AD/ResNet50_BEN/Process_model/quantize/quantize_eval_model.pb
[INFO] parse raw model     :100%|████████████████████████████████▉| 267/268 [00:00<00:00, 22255.59it/s]             
Traceback (most recent call last):
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/bin/xnnc-run", line 33, in <module>
    sys.exit(load_entry_point('xnnc==2.0.0', 'console_scripts', 'xnnc-run')())
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/__main__.py", line 49, in main
    runner.normal_run(args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/runner.py", line 123, in normal_run
    target=target,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/xconverter.py", line 145, in run
    model_files, model_type, _layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/core.py", line 123, in make_xmodel
    model_type=model_t,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 107, in to_xmodel
    model_type,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 173, in create_xmodel
    name, layers, layout, in_shapes, batchsize
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 289, in __create_xmodel_from_tf1
    batchsize,
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/translator/tensorflow_translator.py", line 3337, in __generate_xmodel
    node.src_dtype = TF_TO_NP.get(DT_NAME.get(layer.attr["SrcT"].type))
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib/python3.6/site-packages/xnnc/ir/xnode.py", line 6210, in src_dtype
    assert dtype is not None, "'dtype' should not be None."
AssertionError: 'dtype' should not be None.
```

Has anyone had a similar error? Any help is deeply appreciated. Thanks.

**Comment by zhenzhen-AMD** [comment]
Hi @comihai ，
Please provide the floating point model and the quantized model and the code for the quantized model. thanks.

**Comment by comihai** [comment]
HI @zhenzhen-AMD ,
Thank you for your quick reply. I think that I figured out the problem, but not sure enough. In [Vitis AI User Guide (UG1414)](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/vai_q_tensorflow-Usage) it is recommended as follows:

> Set –input_nodes as the last nodes for pre-processing and –output_nodes as the last nodes for post-processing because some of the operations required for pre- and post-processing are not quantizable and might cause errors when compiled by the Vitis AI compiler if you need to deploy the quantized model to the DPU. The input nodes might not be the same as the placeholder nodes of the graph.

In my case, I was setting the output node to a GreaterEqual outer node applied on Sigmoid(logits). Now, I set output node to "resnet_v1_50/SpatialSqueeze" inner node to get logits and run Sigmoid and GreaterEqual operators on CPU part.

**Comment by zhenzhen-AMD** [comment]
Hi @comihai ,
Has the problem been resolved? Do you have any other questions? If there are no more issues, we will close this issue. There is a problem later, please reopen the issue. Thank you.
