### ISSUE TITLE
Vitis AI 2.5 inspector issue

### ISSUE THREAD

**Issue by ZZZDark** [Xilinx/Vitis-AI#926]
An error occurred while compiling a pytorch quantization model (yolov5) using Vitis ai 2.5. 

My code is as follow:

`

    device = torch.device("cuda:0")
    modelOrigin = DetectPrunedMultiBackend(opt.weights, device=device, dnn=opt.dnn)
    
    inspector = Inspector("DPUCZDX8G_ISA1_B4096")
    input = torch.randn([1, 3, 1024, 1024], device=device)
    inspector.inspect(module = modelOrigin, input_args = input, device = device)
`

the error is:
`
Traceback (most recent call last):
  File "Vai-q-Tianzhi.py", line 105, in <module>
    quantization(opt)
  File "Vai-q-Tianzhi.py", line 89, in quantization
    inspector.inspect(module = modelOrigin, input_args = input, device = device)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/apis.py", line 182, in inspect
    self._inspector_impl.inspect(module, input_args, device, output_dir, verbose_level)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/hardware/inspector.py", line 83, in inspect
    dev_graph = self._prepare_deployable_graph(copied_model, input_args, device, output_dir)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/hardware/inspector.py", line 103, in _prepare_deployable_graph
    _ = quant_module(input_args)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "quantize_result/DetectPrunedMultiBackend.py", line 427, in forward
    output_module_170 = self.module_170(input=output_module_169, other=output_module_9)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/nn/modules/module_template.py", line 131, in forward
    output = caller(*args, **kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
`

I actually choose "cuda:0" as my device in my code. And the docker enviroment I use is built as vitis-ai-gpu:last. But it seem that something in Vai-Quantilizer is using cpu as device? Please help me to solve this problem. Thank you!

**Comment by carrotandjzy** [comment]
https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Quantizer/vai_q_pytorch/pytorch_binding/pytorch_nndct/hardware/inspector.py:101
 **_ = quant_module(*input_args)_** => quant_module.to(device)(*input_args)

 https://github.com/Xilinx/Vitis-AI/blob/master/src/Vitis-AI-Quantizer/vai_q_pytorch/pytorch_binding/pytorch_nndct/hardware/inspector.py:103
**_ = quant_module(input_args)** => _ = quant_module.to(device)(input_args)
