### ISSUE TITLE
Quantization of a PyTorch model stalls during evaluation loop

### ISSUE THREAD

**Issue by daniperfer** [Xilinx/Vitis-AI#950]
Hi,

I'm trying to quantize a pytorch model with Vitis-AI. I have a quantization script which first calls to `torch_quantizer`, and then do an evaluation loop which makes inference on the "quantized" model. However, the execution stalls at this point, during the evaluation loop.
Do anybody have any thoughts on what could be going wrong for having this behavior? 

The model is a slightly modified version of VGG19, which allows the extraction of some intermediate layers:
```
class Vgg19(torch.nn.Module):
    # modified from the original at
    # https://github.com/chenyuntc/pytorch-book/blob/master/chapter08-neural_style/PackedVGG.py

    def __init__(self, batch_normalization=True, required_layers=None):

        if required_layers == None and batch_normalization:
            required_layers = [3, 10, 17, 30, 43, 46]
        elif required_layers == None:
            required_layers = [2, 7, 12, 21, 30, 32]

        # features 2，7，12，21, 30, 32: conv1_2,conv2_2,relu3_2,relu4_2,conv5_2,conv5_3
        super(Vgg19, self).__init__()

        if batch_normalization:
            features = list(models.vgg19_bn(pretrained=True).features)[
                :47]  # get vgg features
            self.avgpool = models.vgg19_bn(pretrained=True).avgpool
            self.classifier = models.vgg19_bn(pretrained=True).classifier
        else:
            features = list(models.vgg19(pretrained=True).features)[
                :33]  # get vgg features
            self.avgpool = models.vgg19(pretrained=True).avgpool
            self.classifier = models.vgg19(pretrained=True).classifier

        # construct network in eval mode
        self.features = torch.nn.ModuleList(features).eval()

        for param in self.features.parameters():  # we don't need gradients, turn them of to save memory
            param.requires_grad = False

        # record required layers to save them in forward
        self.required_layers = required_layers

        for layer in required_layers[:-1]:
            # do not overwrite in any layer
            self.features[layer+1].inplace = False

    def forward(self, x):
        results = []
        for ii, model in enumerate(self.features):
            x = model(x)
            if ii in self.required_layers:
                results.append(x)
        # pass x to head and get output
        x = self.avgpool(x)
        flatten = torch.flatten(x, 1)
        output = self.classifier(flatten)

        return results, output
```

The quantization script is as follows:
```
def load_imagenet_data(
        data_dir='../../data/imagenet-mini',
        batch_size=128,
        subset_len=None,
        sample_method='random',
        target_shape = (224, 224),
        **kwargs):
    # prepare data
    valdir = data_dir + '/val'
    normalize = transforms.Normalize(
        mean=image_mean, std=image_std)
    size = target_shape
    resize = tuple([s+(2*padding_n) for s in list(target_shape)])
    dataset = torchvision.datasets.ImageFolder(
        valdir,
        transforms.Compose([
            transforms.Resize(resize),
            transforms.CenterCrop(size),
            transforms.ToTensor(),
            normalize,
        ]))
    if subset_len:
        assert subset_len <= len(dataset)
        if sample_method == 'random':
            dataset = torch.utils.data.Subset(
                dataset, random.sample(range(0, len(dataset)), subset_len))
        else:
            dataset = torch.utils.data.Subset(
                dataset, list(range(subset_len)))
    data_loader = torch.utils.data.DataLoader(
        dataset, batch_size=batch_size, shuffle=False, **kwargs)
    return data_loader


class AverageMeter(object):
    """Computes and stores the average and current value"""

    def __init__(self, name, fmt=':f'):
        self.name = name
        self.fmt = fmt
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count

    def __str__(self):
        fmtstr = '{name} {val' + self.fmt + '} ({avg' + self.fmt + '})'
        return fmtstr.format(**self.__dict__)


def accuracy_imagenet(output, target, topk=(1,)):
    """Computes the accuracy over the k top predictions
      for the specified values of k"""
    with torch.no_grad():
        maxk = max(topk)
        batch_size = target.size(0)

        _, pred = output.topk(maxk, 1, True, True)
        pred = pred.t()
        correct = pred.eq(target.view(1, -1).expand_as(pred))

        res = []
        for k in topk:
            correct_k = correct[:k].flatten().float().sum(0, keepdim=True)
            res.append(correct_k.mul_(100.0 / batch_size))
        return res


def evaluate_imagenet(model, val_loader, loss_fn, device):
    model.eval()
    model = model.to(device)
    top1 = AverageMeter('Acc@1', ':6.2f')
    top5 = AverageMeter('Acc@5', ':6.2f')
    total = 0
    Loss = 0
    logger.debug(f"len(val_loader) {len(val_loader)}")
    for i, (images, labels) in tqdm(
            enumerate(val_loader), total=len(val_loader)):
        images = images.to(device)
        labels = labels.to(device)
        #pdb.set_trace()
        _, outputs = model(images)
        loss = loss_fn(outputs, labels)
        Loss += loss.item()
        total += images.size(0)
        acc1, acc5 = accuracy_imagenet(outputs, labels, topk=(1, 5))
        top1.update(acc1[0], images.size(0))
        top5.update(acc5[0], images.size(0))
    return top1.avg, top5.avg, Loss / total

def quantize(dset_dir, ann_file, float_model, quant_mode, batch_size, quant_output, subset_len, deploy, input_pairs):

    # ------------------------ MODEL CREATION STARTS -------------------------  
    device = torch.device(f"cuda:0")

    # declare model architecture and load pre-trained weights
    float_model = float_model.upper()
    if float_model == 'VGG19':
        model = Vgg19(batch_normalization=False).to(device)
    elif float_model == 'VGG19_BN':
        model = Vgg19(batch_normalization=True).to(device)
    else:
        logger.error('Error: model {float_model} is not supported!')
        return

    model = model.to(device)
    model.eval()
    # ------------------------ MODEL CREATION ENDS -------------------------
    
    val_loader = load_imagenet_data(
        data_dir=dset_dir,
        subset_len=subset_len,
        batch_size=batch_size,
        sample_method='random',
        target_shape=target_shape)
    logger.info(f"evaluate_imagenet Float model")
    #register_modification_hooks(model_gen, train=False)
    # to get loss value after evaluation
    loss_fn = torch.nn.CrossEntropyLoss().to(device)
    acc1_gen, acc5_gen, loss_gen = evaluate_imagenet(
        model, val_loader, loss_fn, device=device)
    # logging accuracy
    print('loss: %g' % (loss_gen))
    print('top-1 / top-5 accuracy: %g / %g' % (acc1_gen, acc5_gen))

    # override batch_size if in test mode
    if quant_mode != 'test' and deploy:
        deploy = False
        print(r'Warning: Exporting xmodel needs to be done in quantization test mode, turn off it in this running!')
    if deploy and (batch_size != 1 or subset_len != 1):
        print(r'Warning: Exporting xmodel needs batch size to be 1 and only 1 iteration of inference, change them automatically!')
        batch_size = 1
        subset_len = 1

    # ------ QUANTIZE -----------------------------------------------------
    if quant_mode == 'float':
        quantized_model = model
    else:
        logger.info(f"Quantization")
        rand_in = []
        for _ in np.arange(batch_size):
            input_sample = np.random.random_integers(
                0, 255, target_shape + (3,)).astype(np.uint8)
            # just normalize input image and add padding to have dimensions multiple of 16
            rand_tensor, _ = dfm_transform(
                input_sample, device, padding_n=padding_n, mean=image_mean, std=image_std)
            rand_in.append(rand_tensor)

        inputs = torch.cat(rand_in, dim=0)
        quantizer = torch_quantizer(
            quant_mode, model, (inputs), device=device, output_dir=quant_output)
        quantized_model = quantizer.quant_model
    # ---------------------------------------------------------------------

    val_loader = load_imagenet_data(
        data_dir=dset_dir,
        subset_len=subset_len,
        batch_size=batch_size,
        sample_method='random',
        target_shape=target_shape)
    logger.info(f"Evaluation Quantized model")

    #register_modification_hooks(model_gen, train=False)
    # to get loss value after evaluation
    loss_fn = torch.nn.CrossEntropyLoss().to(device)
    # THE EXECUTION STALLS HERE,  INSIDE evaluate_imagenet, when making inference with the quantized_model
    acc1_gen, acc5_gen, loss_gen = evaluate_imagenet(
        quantized_model, val_loader, loss_fn, device=device)

    # logging accuracy
    print('loss: %g' % (loss_gen))
    print('top-1 / top-5 accuracy: %g / %g' % (acc1_gen, acc5_gen))

    # handle quantization results & export config
    if quant_mode == 'calib':
        logger.info(f"Exporting quant config")
        quantizer.export_quant_config()
        print_size_of_model(quantized_model)
    if deploy:
        logger.info(f"Exporting xmodel")
        quantizer.export_xmodel(deploy_check=False, output_dir=quant_output)

    return
```

I've tested this in both Vitis-AI docker 2.0 and 2.5 versions, getting the same results in each one:
```
python quantize_vgg19_features_vai25.py --dset_dir "../../data/imagenet-mini" \
    --float_model "VGG19" \
    --quant_output "./quantization_results_vgg19" \
    --quant_mode calib \
    --subset_len 200 \
    --batch_size 2 \
    --nndct_parse_debug=1
```

In case they are useful, the logging messages I see during the execution of quantization script are:
```
[VAIQ_NOTE]: Loading NNDCT kernels...

-----------------------------------------                                    
PyTorch version :  1.10.1                                                                 
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)                      
[GCC 9.4.0]                                                                                                                                                                                             
-----------------------------------------                                    
 Command line options:       
--dset_dir     :  ../../data/imagenet-mini                                                            
--float_model  :  VGG19                        
--quant_mode   :  calib                                                              
--batch_size   :  2                                                                  
--quant_output :  ./quantization_results_vgg19                               
--subset_len   :  200                                                                                               
--deploy       :  False                                                                                      
-----------------------------------------                                           
2022-08-03 09:54:20.742 | INFO     | __main__:quantize:284 - You have 4 CUDA devices available
2022-08-03 09:54:20.809 | INFO     | __main__:quantize:294 - Selecting device with less allocated memory...

2022-08-03 09:54:20.810 | INFO     | __main__:quantize:309 - loading VGG19...
2022-08-03 09:54:29.472 | INFO     | __main__:quantize:311 - model is loaded.
/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_trace.py:965: TracerWarning: Encountering a list at the output of the tracer might cause the trace to be incorrect, this is only v
alid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you
absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.          
  argument_names,                                                                           
2022-08-03 09:54:30.617 | INFO     | __main__:quantize:330 - load detector from: VGG19
2022-08-03 09:54:30.617 | INFO     | __main__:quantize:331 - device = cuda:0

2022-08-03 09:54:31.763 | INFO     | __main__:quantize:364 - evaluate_imagenet Float model
2022-08-03 09:54:31.764 | DEBUG    | __main__:evaluate_imagenet:167 - len(val_loader) 100
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:07<00:00, 12.55it/s]
loss: 3.46008
top-1 / top-5 accuracy: 0 / 0
2022-08-03 09:54:39.734 | INFO     | __main__:quantize:387 - Quantization

[VAIQ_NOTE]: Quant config file is empty, use default quant configuration

[VAIQ_NOTE]: Quantization calibration process start up...

[VAIQ_NOTE]: =>Quant Module is in 'cuda'.

[VAIQ_NOTE]: =>Parsing Vgg19...

[VAIQ_NOTE]: Start to trace model...

[VAIQ_NOTE]: Finish tracing.

[VAIQ_NOTE]: Processing ops...
██████████████████████████████████████████████████| 44/44 [00:00<00:00, 2050.00it/s, OpInfo: name = return_0, type = Return]

[VAIQ_NOTE]: =>Doing weights equalization...

[VAIQ_NOTE]: =>Quantizable module is generated.(./quantization_results_vgg19/Vgg19.py)

[VAIQ_NOTE]: =>Get module with quantization.
2022-08-03 09:54:43.543 | INFO     | __main__:quantize:419 - Evaluation Quantized model
2022-08-03 09:54:43.545 | DEBUG    | __main__:evaluate_imagenet:167 - len(val_loader) 100
  0%|                                                                                                                                                                      | 0/100 [00:00<?, ?it/s]> /opt/vitis_ai/
---- EXECUTINON STALLS HERE ----
```

Do anybody have any thoughts on what could be going wrong for having this behavior?

**Comment by niuxjxlnx** [comment]
@daniperfer :
 
Can you paste the python stack here? You can type CTRL+C or use pdb to get the stack.
Other information may helps (type nvidia-smi to get the information):
1) GPU dirver version and GPU card architecture in your server
2) How many memory on the GPU card

**Comment by daniperfer** [comment]
Thanks for replying, @niuxjxlnx:

I've tried to type CTRL+C when the execution of my script stalled, but it hasn't respond to the command. So I've used pdb for running it step by step. I've run it several times so as to find what was the last line which I could run. Finally, I think it occurs just after the line 
```
"/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/nn/modules/fix_ops.py", line 132, in NndctDiffsFixPos
    torch.ops.vai.diffs_fix_pos(Tinput, Tbuffer, Tfixpos, bit_width, range, method, device_id)
```

The whole stack is as follows:
```
[VAIQ_NOTE]: Loading NNDCT kernels...                                                                                                                                                                              

-----------------------------------------                                                                                                                                                                          
PyTorch version :  1.10.1                                                                                                                                                                                          
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)                                                                                                                                                
[GCC 9.4.0]                                                                                                                                                                                                        
-----------------------------------------                                                                                                                                                                          
 Command line options:                                                                                                                                                                                             
--dset_dir     :  ../../data/imagenet-mini                                                                                                                                                                         
--ann_file     :  dataset/annotation/image_info_test2017.json                                      
--float_model  :  VGG19                                                              
--quant_mode   :  calib                                                                                                     
--batch_size   :  2                                                                                                 
--quant_output :  ./quantization_results_vgg19                                                               
--subset_len   :  200                                                                  
--deploy       :  False                                                                                                      
--input_pairs  :  image_pairs_jp.txt                                         
-----------------------------------------

2022-08-29 14:22:03.531 | INFO     | __main__:quantize:283 - You have 4 CUDA devices available
2022-08-29 14:22:03.588 | INFO     | __main__:quantize:293 - Selecting device with less allocated memory...
2022-08-29 14:22:03.589 | DEBUG    | __main__:quantize:294 - Devices memory status (sorted) [('GeForce RTX 3090', 24268.0, 2107.0), ('GeForce RTX 3090', 24268.0, 2.0), ('GeForce RTX 2080 Ti', 11019.0, 3.0), ('GeForce RTX 2080 Ti', 11019.0, 3.0)]                                                        
2022-08-29 14:22:03.589 | INFO     | __main__:quantize:308 - loading VGG19...                                 
2022-08-29 14:22:13.102 | INFO     | __main__:quantize:310 - model is loaded.                                                                                                                                      
2022-08-29 14:22:14.445 | INFO     | __main__:quantize:329 - load detector from: VGG19                            
2022-08-29 14:22:14.446 | INFO     | __main__:quantize:330 - device = cuda:1

2022-08-29 14:22:15.463 | INFO     | __main__:quantize:363 - evaluate_imagenet Float model
2022-08-29 14:22:15.464 | DEBUG    | __main__:evaluate_imagenet:167 - len(val_loader) 100
loss: 3.45729
top-1 / top-5 accuracy: 0.5 / 0.5
2022-08-29 14:22:21.333 | INFO     | __main__:quantize:386 - Quantization
quantize_vgg19_features_vai25.py:390: DeprecationWarning: This function is deprecated. Please call randint(0, 255 + 1) instead
  0, 255, target_shape + (3,)).astype(np.uint8)

[VAIQ_NOTE]: Quant config file is empty, use default quant configuration

[VAIQ_NOTE]: Quantization calibration process start up...

[VAIQ_NOTE]: =>Quant Module is in 'cuda'.

[VAIQ_NOTE]: =>Parsing Vgg19...

[VAIQ_NOTE]: Start to trace model...

[VAIQ_NOTE]: Finish tracing.

[VAIQ_NOTE]: Processing ops...
██████████████████████████████████████████████████| 44/44 [00:00<00:00, 2044.82it/s, OpInfo: name = return_0, type = Return]

[VAIQ_NOTE]: =>Doing weights equalization...

[VAIQ_NOTE]: =>Quantizable module is generated.(./quantization_results_vgg19/Vgg19.py)

[VAIQ_NOTE]: =>Get module with quantization.

2022-08-29 14:22:24.949 | INFO     | __main__:quantize:418 - Evaluation Quantized model
> /workspace/andante/MM-PR-01326-ANDANTE-image_registration/quantize_vgg19_features_vai25.py(424)quantize()
-> acc1_gen, acc5_gen, loss_gen = evaluate_imagenet(
(Pdb) c
2022-08-29 14:55:06.521 | DEBUG    | __main__:evaluate_imagenet:167 - len(val_loader) 100
  0%|                                                                                                                                                                                      | 0/100 [00:00<?, ?it/s]
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/nn/modules/fix_ops.py(131)NndctDiffsFixPos()
-> if support_onnx_export():     
(Pdb) n
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/nn/modules/fix_ops.py(132)NndctDiffsFixPos()
-> torch.ops.vai.diffs_fix_pos(Tinput, Tbuffer, Tfixpos, bit_width, range, method, device_id)
(Pdb) s
--Call--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(78)__getattr__()                 
-> def __getattr__(self, name):
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(80)__getattr__()                 
-> namespace = _OpNamespace(name)
(Pdb) s
--Call--                                                                                                               
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(52)__init__()
-> def __init__(self, name):
(Pdb) s   
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(53)__init__()                                                                                                                -> super(_OpNamespace, self).__init__('torch.ops.' + name)
(Pdb) s                 
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(54)__init__()
-> self.name = name
(Pdb) s                                                                                                                     
--Return--                          
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(54)__init__()->None
-> self.name = name                                                                                   
(Pdb) s                      
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(81)__getattr__()
-> setattr(self, name, namespace)                                                                     
(Pdb) s                                             
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(82)__getattr__()
-> return namespace                                                                                   
(Pdb) s     
--Return--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(82)__getattr__()-><module 'torc...m 'torch.ops'>
-> return namespace                                                                                                                   
(Pdb) s     
--Call--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(56)__getattr__()
-> def __getattr__(self, op_name):
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(58)__getattr__()
-> if op_name == '__file__':
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(62)__getattr__()
-> qualified_op_name = '{}::{}'.format(self.name, op_name)
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(63)__getattr__()
-> op = torch._C._jit_get_operation(qualified_op_name)
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(66)__getattr__()
-> torch.jit._builtins._register_builtin(op, qualified_op_name)
(Pdb) s
--Call--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(160)_register_builtin()
-> def _register_builtin(fn, op):
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(161)_register_builtin()
-> _get_builtin_table()[id(fn)] = op
(Pdb) s
--Call--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(129)_get_builtin_table()
-> def _get_builtin_table():
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(131)_get_builtin_table()
-> if _builtin_table is not None:
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(132)_get_builtin_table()
-> return _builtin_table
(Pdb) s
--Return--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(132)_get_builtin_table()->{94156416326432: 'aten::dict', 94156416479168: 'aten::dict', 94156426984032: 'aten::autoca
st', 94156475397984: 'aten::FatalError', ...}
-> return _builtin_table
(Pdb) s
--Return--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/jit/_builtins.py(161)_register_builtin()->None
-> _get_builtin_table()[id(fn)] = op
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(67)__getattr__()
-> setattr(self, op_name, op)
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(68)__getattr__()
-> op.__module__ = self.__module__ + "." + self.name
(Pdb) s
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(69)__getattr__()
-> return op
(Pdb) s
--Return--
> /opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py(69)__getattr__()-><built-in met...x7fc411fc5240>
-> return op
(Pdb) q 0%|                                                                                                                                                                                      | 0/100 [01:21<?, ?it/s]
Traceback (most recent call last):
  File "quantize_vgg19_features_vai25.py", line 532, in <module>
    run_main()
  File "quantize_vgg19_features_vai25.py", line 526, in run_main
    args.input_pairs)
  File "quantize_vgg19_features_vai25.py", line 423, in quantize
    acc1_gen, acc5_gen, loss_gen = evaluate_imagenet(quantized_model, val_loader, loss_fn, device=device)
  File "quantize_vgg19_features_vai25.py", line 172, in evaluate_imagenet
    _, outputs = model(images)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./quantization_results_vgg19/Vgg19.py", line 51, in forward
    output_module_0 = self.module_0(input=args[0])
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/nn/modules/prim_ops.py", line 122, in forward
    output = quantize_tensors([output], self.node)[0]
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/nndct_shared/quantization/utils.py", line 91, in quantize_tensors
    tensor_type))
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/quantization/torchquantizer.py", line 160, in do_scan
    method = mth)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/nn/modules/fix_ops.py", line 132, in NndctDiffsFixPos
    torch.ops.vai.diffs_fix_pos(Tinput, Tbuffer, Tfixpos, bit_width, range, method, device_id)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/torch/_ops.py", line 69, in __getattr__
    return op
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/bdb.py", line 92, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/bdb.py", line 154, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
```

The nvidia-smi command was showing the following information when my process stalled. My process is the one with the PID 16402
```
(base) dpereira@machinelearning:$ nvidia-smi
Mon Aug 29 16:43:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090    Off  | 00000000:18:00.0 Off |                  N/A |
| 30%   41C    P2   105W / 350W |   3806MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:3B:00.0 Off |                  N/A |
|  0%   40C    P8     9W / 260W |      3MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 3090    Off  | 00000000:86:00.0 Off |                  N/A |
| 53%   53C    P2   117W / 350W |   7949MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:AF:00.0 Off |                  N/A |
|  0%   41C    P8    21W / 260W |      3MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      8504      C   /opt/conda/bin/python            2105MiB |
|    0   N/A  N/A     16402      C   python                           1699MiB |
|    2   N/A  N/A     16402      C   python                           7947MiB |
+-----------------------------------------------------------------------------+
```

I am using the Vitis-AI docker version 2.5.

**Comment by niuxjxlnx** [comment]
@daniperfer 

How about the status of "--quant_mode float"? I mean inference the model without quantization. Stalls during inference or not?

**Comment by niuxjxlnx** [comment]
@daniperfer 
In the following part of code, what's the shape of rand_in? 
```
    if quant_mode == 'float':
        quantized_model = model
    else:
        logger.info(f"Quantization")
        rand_in = []
        for _ in np.arange(batch_size):
            input_sample = np.random.random_integers(
                0, 255, target_shape + (3,)).astype(np.uint8)
            # just normalize input image and add padding to have dimensions multiple of 16
            rand_tensor, _ = dfm_transform(
                input_sample, device, padding_n=padding_n, mean=image_mean, std=image_std)
            rand_in.append(rand_tensor)

        inputs = torch.cat(rand_in, dim=0)
        quantizer = torch_quantizer(
            quant_mode, model, (inputs), device=device, output_dir=quant_output)
```

**Comment by daniperfer** [comment]
Hi, @niuxjxlnx:

`rand_in` is a list of length B (B for batch length) which contains three-dimesional pytorch tensors (which are supposed to be images).

I've tested it with batches 1, 2 and 4, and I've set width=height for the rand images; and I've got the following shapes for the tensors inside `rand_in`:

with batch 1:
```
2022-09-01 12:20:37.537 | DEBUG    | __main__:quantize:396 - len(rand_in)=1
2022-09-01 12:20:37.537 | DEBUG    | __main__:quantize:398 - rand_in[0].shape=torch.Size([1, 3, 640, 640])
2022-09-01 12:20:37.538 | DEBUG    | __main__:quantize:406 - inputs.shape = torch.Size([1, 3, 640, 640])
```

with batch 2:
```
2022-09-01 12:22:27.610 | DEBUG    | __main__:quantize:396 - len(rand_in)=2
2022-09-01 12:22:27.611 | DEBUG    | __main__:quantize:398 - rand_in[0].shape=torch.Size([1, 3, 640, 640])
2022-09-01 12:22:27.612 | DEBUG    | __main__:quantize:398 - rand_in[1].shape=torch.Size([1, 3, 640, 640])
2022-09-01 12:22:27.613 | DEBUG    | __main__:quantize:406 - inputs.shape = torch.Size([2, 3, 640, 640])
```

with batch 4:
```
2022-09-01 15:49:29.682 | DEBUG    | __main__:quantize:396 - len(rand_in)=4
2022-09-01 15:49:29.683 | DEBUG    | __main__:quantize:398 - rand_in[0].shape=torch.Size([1, 3, 640, 640])
2022-09-01 15:49:29.683 | DEBUG    | __main__:quantize:398 - rand_in[1].shape=torch.Size([1, 3, 640, 640])
2022-09-01 15:49:29.683 | DEBUG    | __main__:quantize:398 - rand_in[2].shape=torch.Size([1, 3, 640, 640])
2022-09-01 15:49:29.683 | DEBUG    | __main__:quantize:398 - rand_in[3].shape=torch.Size([1, 3, 640, 640])
2022-09-01 15:49:29.684 | DEBUG    | __main__:quantize:406 - inputs.shape = torch.Size([4, 3, 640, 640])
```

**Comment by daniperfer** [comment]
Hi:

I've finally found a way of avoiding the stalling problem I was having. It have to do with strictly using a single GPU for running the process.

I don't know what is exactly the reason, but the process was always running through several GPUs (I could observe that in nvidia-smi output) in spite of specifying only one of them by using the line 
`device = torch.device(f"cuda:{gpu_idx}")`
at the beginning of my script. 

So I tried to limit the number of GPUs the process could see, so as to run as if there were just a single GPU. I put the following lines at the beginning of my python script:
```
os.environ["CUDA_VISIBLE_DEVICES"] = str(gpu_idx)
device = torch.device(f"cuda:0")
```
And this way the process does not stall: the quantization script run complete until the end.

So I am using this solution from now on to prevent my process from stalling.

**Comment by niuxjxlnx** [comment]
@daniperfer : 

Using different GPU cards in one server may face to extra risk of GPU memory accessing, which is also what I want you help verify. This is also the reason why I cannot repeat the same problem in my own server, on which 4 same GPU cards are installed.
