### ISSUE TITLE
Error when exporting a PyTorch quantized model

### ISSUE THREAD

**Issue by daniperfer** [Xilinx/Vitis-AI#998]
Hi:

I'm trying to quantize and compile a pytorch model with Vitis-AI (version 2.5). I have a quantization script with all the required steps.

First of all, I run the script specifying `quant_mode=calib`, and I get the expected result from the quantization step: files `quant_info.json` and `Vgg19.py` in the output folder:
 
```
-rw-r--r-- 1 vitis-ai-user vitis-ai-group   3005 Sep  2 12:38 quant_info.json
-rw-r--r-- 1 vitis-ai-user vitis-ai-group   9363 Sep  2 12:38 Vgg19.py
```

However, the following error occurs when exporting the model with `quant_mode=test` and flag `--deploy`:
```

2022-09-02 11:54:37.613 | INFO     | __main__:quantize:474 - Exporting xmodel

[VAIQ_NOTE]: =>Converting to xmodel ...

Traceback (most recent call last):
  File "quantize_vgg19_features_vai25.py", line 554, in <module>
    run_main()
  File "quantize_vgg19_features_vai25.py", line 548, in run_main
    args.input_pairs)
  File "quantize_vgg19_features_vai25.py", line 475, in quantize
    quantizer.export_xmodel(deploy_check=False, output_dir=quant_output)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/apis.py", line 127, in export_xmodel
    self.processor.export_xmodel(output_dir, deploy_check)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/qproc/base.py", line 248, in export_xmodel
    dump_xmodel(output_dir, deploy_check, self._lstm_app)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/qproc/base.py", line 321, in dump_xmodel
    deploy_graphs = get_deploy_graph_list(quantizer.quant_model, quantizer.Nndctgraph)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/qproc/utils.py", line 283, in get_deploy_graph_list
    g_optmizer.layout_tranform()    
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/nndct_shared/compile/deploy_optimizer.py", line 445, in layout_tranform
    if pn.transpose_out_order is None and pn.out_tensors[0].ndim and node.out_tensors[0].ndim and pn.out_tensors[0].ndim == node.out_tensors[0].ndim:
IndexError: list index out of range
```

Do anybody have any thoughts on how this could be solved?

---
As an additional test, if I use the Inspector (even before the quantization step), I also get the same error:

```
device = torch.device(f"cuda:0")
.
...
.
model = model.to(device)
model.eval()
target_shape = (224, 224)
example_inputs = torch.randn([batch_size, 3, target_shape[1], target_shape[0]]).to(device)
logger.debug(f"example_inputs.shape={example_inputs.shape}")
inspector = Inspector("DPUCZDX8G_ISA1_B4096")
inspector.inspect(model, example_inputs, device)
```

The error message in this case is the same as above, although the Traceback is not exactly the same:

```
2022-09-02 12:02:58.840 | DEBUG    | __main__:quantize:343 - example_inputs.shape=torch.Size([2, 3, 224, 224])

[VAIQ_NOTE]: =>Inspector is initialized successfully with target:
name: DPUCZDX8G_ISA1_B4096
type: DPUCZDX8G
isa_version: 1

[VAIQ_NOTE]: =>Start to inspect model...

[VAIQ_NOTE]: =>Quant Module is in 'cuda'.

[VAIQ_NOTE]: =>Parsing Vgg19...

[VAIQ_NOTE]: Start to trace model...

[VAIQ_NOTE]: Finish tracing.

[VAIQ_NOTE]: Processing ops...
██████████████████████████████████████████████████| 44/44 [00:00<00:00, 1790.06it/s, OpInfo: name = return_0, type = Return]                                             

[VAIQ_NOTE]: =>Doing weights equalization...

[VAIQ_NOTE]: =>Quantizable module is generated.(quantize_result/Vgg19.py)
Traceback (most recent call last):
  File "quantize_vgg19_features_vai25.py", line 551, in <module>
    run_main()
  File "quantize_vgg19_features_vai25.py", line 545, in run_main
    args.input_pairs)
  File "quantize_vgg19_features_vai25.py", line 346, in quantize
    inspector.inspect(model, example_inputs, device)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/apis.py", line 182, in inspect
    self._inspector_impl.inspect(module, input_args, device, output_dir, verbose_level)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/hardware/inspector.py", line 83, in inspect
    dev_graph = self._prepare_deployable_graph(copied_model, input_args, device, output_dir)
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/pytorch_nndct/hardware/inspector.py", line 110, in _prepare_deployable_graph
    g_optmizer.layout_tranform()    
  File "/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/nndct_shared/compile/deploy_optimizer.py", line 445, in layout_tranform
    if pn.transpose_out_order is None and pn.out_tensors[0].ndim and node.out_tensors[0].ndim and pn.out_tensors[0].ndim == node.out_tensors[0].ndim:
IndexError: list index out of range
```

---
The model I am using is a slightly modified version of VGG19, which allows the extraction of some intermediate layers:

```
class Vgg19(torch.nn.Module):

    # modified from the original @ https://github.com/chenyuntc/pytorch-book/blob/master/chapter08-neural_style/PackedVGG.py

    def __init__(self, batch_normalization=True, required_layers=None):

        if required_layers == None and batch_normalization:
            required_layers = [3, 10, 17, 30, 43, 46]
        elif required_layers == None:
            required_layers = [2, 7, 12, 21, 30, 32]

        # features 2，7，12，21, 30, 32: conv1_2,conv2_2,relu3_2,relu4_2,conv5_2,conv5_3
        super(Vgg19, self).__init__()

        if batch_normalization:
            features = list(models.vgg19_bn(pretrained=True).features)[
                :47]  # get vgg features
            self.avgpool = models.vgg19_bn(pretrained=True).avgpool
            self.classifier = models.vgg19_bn(pretrained=True).classifier
        else:
            features = list(models.vgg19(pretrained=True).features)[
                :33]  # get vgg features
            self.avgpool = models.vgg19(pretrained=True).avgpool
            self.classifier = models.vgg19(pretrained=True).classifier

        # construct network in eval mode
        self.features = torch.nn.ModuleList(features)

        # record required layers to save them in forward
        self.required_layers = required_layers


    def forward(self, x):
        results = []
        for ii, model in enumerate(self.features):
            x = model(x)
            if ii in self.required_layers:
                results.append(x)
        # x to head and get output
        x = self.avgpool(x)
        flatten = torch.flatten(x, 1)
        output = self.classifier(flatten)

        return results, output
```

**Comment by niuxjxlnx** [comment]
@daniperfer 

This is a bug in vitis-ai pytorch quantizer 2.5 version. You can bypass it by change the code in file 
/opt/vitis_ai/conda/envs/vitis-ai-pytorch/lib/python3.7/site-packages/nndct_shared/compile/deploy_optimizer.py，near line 443, to the following code:

```
      **if len(node.in_nodes) <= 1 or len(node.out_nodes) == 0 or node in implicit_ops:
        continue**
      if pn.transpose_out_order is None and pn.out_tensors[0].ndim and node.out_tensors[0].ndim and pn.out_tensors[0].ndim == node.out_tensors[0].ndim:

```

**Comment by daniperfer** [comment]
Thanks, @niuxjxlnx:
After having applied your solution above, I was able to export the model.
